FROM node:24-slim
RUN npm install -g pnpm@10.26.1
WORKDIR /app
COPY . .
RUN pnpm install --no-frozen-lockfile
RUN pnpm --filter @workspace/api-server run build
CMD ["node", "--enable-source-maps", "artifacts/api-server/dist/index.mjs"]
