FROM node:24-slim
RUN npm install -g pnpm@10.26.1
WORKDIR /app
COPY . .
RUN pnpm install --no-frozen-lockfile
ENV PORT=3000 BASE_PATH=/
RUN pnpm --filter @workspace/tech-blog run build
CMD ["node", "--enable-source-maps", "artifacts/tech-blog/dist/server.mjs"]
