import { Router, type IRouter } from "express";
import healthRouter from "./health";
import postsRouter from "./posts";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import contactRouter from "./contact";
import statsRouter from "./stats";
import adminRouter from "./admin";
import generateRouter from "./generate";
import sitemapRouter from "./sitemap";
import feedRouter from "./feed";
import storageRouter from "./storage";
import imageTransformRouter from "./imageTransform";
import ogImageRouter from "./ogImage";
import authorsRouter from "./authors";
import tagsRouter from "./tags";
import seriesRouter from "./series";
import searchRouter from "./search";
import jobsRouter from "./jobs";
import reviewsRouter from "./reviews";
import advertiseRouter from "./advertise";
import newsletterRouter from "./newsletter";
import auditRouter from "./audit";
import commentsRouter from "./comments";
import analyticsRouter from "./analytics";

const router: IRouter = Router();

router.use(healthRouter);
router.use(postsRouter);
router.use(categoriesRouter);
router.use(productsRouter);
router.use(contactRouter);
router.use(statsRouter);
router.use(adminRouter);
router.use(generateRouter);
router.use(sitemapRouter);
router.use(feedRouter);
router.use(imageTransformRouter);
router.use(ogImageRouter);
router.use(authorsRouter);
router.use(tagsRouter);
router.use(seriesRouter);
router.use(searchRouter);
router.use(storageRouter);
router.use(jobsRouter);
router.use(reviewsRouter);
router.use(advertiseRouter);
router.use(newsletterRouter);
router.use(auditRouter);
router.use(commentsRouter);
router.use(analyticsRouter);

export default router;
