import { Router, type IRouter } from "express";
import healthRouter from "./health";
import postsRouter from "./posts";
import categoriesRouter from "./categories";
import contactRouter from "./contact";
import statsRouter from "./stats";
import adminRouter from "./admin";
import generateRouter from "./generate";
import sitemapRouter from "./sitemap";
import feedRouter from "./feed";
import storageRouter from "./storage";
import imageTransformRouter from "./imageTransform";
import ogImageRouter from "./ogImage";
import authorsRouter from "./authors";
import tagsRouter from "./tags";
import seriesRouter from "./series";
import searchRouter from "./search";
import jobsRouter from "./jobs";
import advertiseRouter from "./advertise";
import newsletterRouter from "./newsletter";
import auditRouter from "./audit";
import commentsRouter from "./comments";
import analyticsRouter from "./analytics";
import sendEmailRouter from "./sendEmail";
import mediaRouter from "./media";
import settingsRouter from "./settings";
import maintenanceRouter from "./maintenance";
import automationRouter from "./automation";
import mcpRouter from "./mcp";

const router: IRouter = Router();

router.use(healthRouter);
router.use(postsRouter);
router.use(categoriesRouter);
router.use(contactRouter);
router.use(statsRouter);
router.use(adminRouter);
router.use(generateRouter);
router.use(sitemapRouter);
router.use(feedRouter);
router.use(imageTransformRouter);
router.use(ogImageRouter);
router.use(authorsRouter);
router.use(tagsRouter);
router.use(seriesRouter);
router.use(searchRouter);
router.use(storageRouter);
router.use(jobsRouter);
router.use(advertiseRouter);
router.use(newsletterRouter);
router.use(auditRouter);
router.use(commentsRouter);
router.use(analyticsRouter);
router.use(sendEmailRouter);
router.use(mediaRouter);
router.use(settingsRouter);
router.use(maintenanceRouter);
router.use(automationRouter);
router.use(mcpRouter);

export default router;
